Algoritmo "ExibeDoNumero1ao50"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Exibe de 1 a 50
// Autor(a)    : Danilo Oliveira de Almeida
// Data atual  : 23/09/2022
Var
// Seção de Declarações das variáveis
numero:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto numero<50 faca
numero<-numero+1
escreval(numero)
fimenquanto

Fimalgoritmo